# Generated by Django 4.0.4 on 2022-05-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_alter_delivery_image_shipper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='subject',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('name', 'category')},
        ),
        migrations.AddField(
            model_name='shipper',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='ships.tag'),
        ),
    ]
