# Generated by Django 4.0.4 on 2022-05-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='order',
        ),
        migrations.AlterField(
            model_name='comment',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ships.shipper'),
        ),
    ]
