# Generated by Django 4.0.4 on 2022-05-10 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0008_comment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='shipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ships.shipper'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.order')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.shipper')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
