# Generated by Django 4.0.4 on 2022-05-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0011_action_rating_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Like'), (2, 'Dislike'), (1, 'Heart')], default=0),
        ),
    ]
