# Generated by Django 4.0.4 on 2022-05-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0013_alter_shipper_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='order',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='shipper',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
