# Generated by Django 4.0.4 on 2022-05-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0016_action_creator_rating_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='order',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='order',
        ),
    ]
